FROM python:3.10-slim

WORKDIR /app

# Копируем зависимости
COPY requirements.txt .

# Устанавливаем Python зависимости
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Копируем код бота
COPY . .

# Создаем необходимые папки
RUN mkdir -p /app/data /app/bot_images && \
    chmod 777 /app/data /app/bot_images

# Запускаем бота
CMD ["python", "bot.py"]