FROM python:3.10-slim

WORKDIR /app

# Копируем requirements.txt
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir python-telegram-bot telethon

# Копируем весь проект
COPY . .

# Создаем папки если их нет
RUN mkdir -p /app/data /app/bot_images && \
    chmod 777 /app/data /app/bot_images

# Запускаем бота (теперь bot.py ВНУТРИ этой папки)
CMD ["python", "bot.py"]
